app:
  sb: Spring Boot Dev
  name: app Dev
  des: "Hello ${app.sb}, ${app.name}!"

  ######################## JDBC MySQL  alibaba Druid 连接池 ########################
  ## initialSize：初始化连接大小
  ## maxActive：连接池最大使用连接数量>>最大并发连接数
  ## maxIdle：最大空闲连接数
  ## minIdle：连接池最小空闲
  ## maxWait：配置获取连接等待超时的时间
  #removeAbandoned：超过时间限制是否回收
  #removeAbandonedTimeout：超过时间限制多长
  #timeBetweenEvictionRunsMillis：配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  #minEvictableIdleTimeMillis：配置一个连接在池中最小生存的时间，单位是毫
  ## validationQuery：用来检测连接是否有效的sql，要求是一个查询语句
  #testWhileIdle：申请连接的时候检测
  #testOnBorrow：申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
  #testOnReturn：归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
  #poolPreparedStatements
  #maxPoolPreparedStatementPerConnectionSize
  ##filter：    监控统计用的filter:stat;日志用的filter:log4j; 防御SQL注入的filter:wall。需要在web.xml中加入servlet、filter;否则报错。
  #访问监控页面：http://ip：port/projectName/druid/index.html
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mypay1.devdb.alipay.net/test_boot?useUnicode=true&amp;characterEncoding=UTF-8
    username: mobile
    password: ali88
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#typeAliasesPackage：它一般对应我们的实体类所在的包，这个时候会自动取对应包中不包括包名的简单类名作为包括包名的别名
#。多个package之间可以用逗号或者分号等来进行分隔。(value的值一定要是包的全名)
mybatis:
  mapperLocations:  classpath:mybatis/mapper/*.xml
  typeAliasesPackage: com.core.dao.mapper.model
  config: classpath:mybatis/mybatis-config.xml

#日志框架-自定义 classpath:config/logback-spring-dev.xml
logging:
    config: classpath:log4j2/log4j2-spring-dev.yml